# Generated by Django 4.2.28 on 2026-02-22 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingsGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of your savings goal (e.g., New Laptop, Vacation)",
                        max_length=100,
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount you want to save",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(1.0)],
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount saved so far",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "deadline",
                    models.DateField(help_text="Target date to achieve this goal"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this goal",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Categories that contribute to this goal",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "ordering": ["deadline", "name"],
            },
        ),
    ]
