# Generated by Django 4.2.28 on 2026-02-22 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., Groceries, Rent, Salary)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the category",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "budget_limit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly budget limit for this category",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("primary", "Blue"),
                            ("success", "Green"),
                            ("danger", "Red"),
                            ("warning", "Yellow"),
                            ("info", "Light Blue"),
                            ("secondary", "Gray"),
                            ("dark", "Black"),
                            ("purple", "Purple"),
                            ("orange", "Orange"),
                        ],
                        default="primary",
                        help_text="Color for UI display",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
    ]
